---
- name: Install httpd
  hosts: Cloud
  remote_user: ec2-user
  become: true
  
  tasks:
    - name: install yum httpd package
      yum:
        name: httpd
        state: present

    - name: Download CSCC1030 zip file from GitHub
      get_url:
        url: https://github.com/wessamabdelwahab/CSCC1030/archive/refs/heads/master.zip
        dest: /home/ec2-user/Cloud.zip

    - name: Unarchive Cloud computing page to web root
      unarchive:
        src: /home/ec2-user/Cloud.zip
        dest: /var/www/html/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Start and Enable httpd
      systemd:
        name: httpd
        state: started
        enabled: true



