---
- name: Install httpd and deploy Cloud page from CSCC1030
  hosts: Cloud
  remote_user: ec2-user
  become: true
  
  tasks:
    - name: Install yum httpd package
      yum:
        name: httpd
        state: present

    - name: Download CSCC1030 zip file from GitHub
      get_url:
        url: https://github.com/wessamabdelwahab/CSCC1030/archive/refs/heads/master.zip
        dest: /home/ec2-user/Cloud.zip

    - name: Unarchive Cloud computing page to web root
      unarchive:
        src: /home/ec2-user/Cloud.zip
        dest: /var/www/html/
        remote_src: yes
      # Removed extra_opts because '--strip-components=1' is not supported

    - name: Move extracted files to web root
      shell: |
        if [ -d /var/www/html/CSCC1030-master ]; then
          mv /var/www/html/CSCC1030-master/* /var/www/html/
          rm -rf /var/www/html/CSCC1030-master
        fi
      args:
        executable: /bin/bash

    - name: Start and Enable httpd
      systemd:
        name: httpd
        state: started
        enabled: true
